dist: xenial

language: node_js
node_js:
  - 15
branches:
  only:
    - master
    - test
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - fatycabada@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

  
addons:
  sonarcloud:
    organization: $ORGANIZATION_TOKEN
    token: $SONAR_TOKEN
script:
  - npm run test:unit
  - sonar-scanner -X 
after_script:
  - cat./coverage/cov.info | coveralls
